### ISSUE TITLE
pgcacher -top -limit 5 不准确

### ISSUE THREAD

**Issue by vearne** [rfyiamcool/pgcacher#12] opened 2023-03-17 01:25 UTC
比如我执行
```
cat /data/file4g &> /dev/null
```
进程退出后，page cache是有缓存这个文件的。但是pgcacher -top -limit 5 无法扫描出

**Comment by rfyiamcool** [comment] 2023-03-19 04:08
I probably know what the problem is. pgcacher scans the collection of files opened by the process. If the file is closed by the process, it cannot be traced. Because pgcacher cannot know which files he has opened.

**Closed as completed by rfyiamcool** 2023-03-19 04:08 UTC
